import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Credit Card Company!
        </h1>

        <p className={styles.description}>
          {' '}
          <code className={styles.code}>The card chooses the spender, remember...</code>
        </p>

        <div className={styles.grid}>

          <a className={styles.card}>
          <label for="name"><h2>Your Name: </h2></label>
          <input type="text" id="name" name="name"></input>
            <a href = "">
             <h3>Sign Up Now &rarr;</h3>  
            </a>         
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        Powered by Bob.
      </footer>
    </div>
  )
}
